Feature/aureus events
ringpublishing/RingPublishingTracking-Android pull request #9
Opened 2021-10-13 14:31 UTC by gmalopolski

2021-10-14 05:55 UTC, adamszeremeta requested changes
Aureus event do poprawy

2021-10-15 11:10 UTC, gmalopolski commented on RingPublishingTracking/src/test/java/com/ringpublishing/tracking/internal/factory/EventsFactoryTest.kt
> +		Assert.assertEquals("111%2C222%2C333", event.parameters[UserEventParam.USER_ACTION_PAYLOAD.text])
zmienione

2021-10-15 11:40 UTC, gmalopolski commented on RingPublishingTracking/src/main/java/com/ringpublishing/tracking/internal/factory/EventsFactory.kt
> +				parameters[UserEventParam.PAGE_VIEW_CONTENT_INFO.text] = "PV_4_${sourceSystemName.trim()}_${publicationId?.trim()}_${contentPartIndex}_$paid"
zmienione

2021-10-15 12:35 UTC, adamszeremeta approved these changes

2021-10-18 07:45 UTC, merged